import { afterEach, describe, expect, it, vi } from 'vitest'
import { CodexClient, codexRequestResult } from './adapters/codex.js'
import { answerCodexQuestion, parseCodexQuestionInput, type CodexQuestionContext } from './codexQuestions.js'
import { QuestionService, parseAskUserQuestionInput, parseQuestionAnswers } from './questions.js'
import { Journal } from './journal.js'
import { AgentWorker } from './agentWorker.js'
import { InProcessExecutor } from './executor.js'

// Shape generated by the pinned app-server 0.153.3, not a Claude SDK question.
const input = {
  threadId: 'thread', turnId: 'turn', itemId: 'item', isBlocking: false,
  questions: [
    { id: 'mode', header: 'Mode', question: 'Choose an answer', isOther: false, isSecret: false,
      options: [{ label: 'Quick', description: '' }, { label: 'Deep', description: 'Full pass' }] },
    { id: 'secret', header: 'Key', question: 'Choose an answer', isSecret: true, options: null },
  ],
}
const journals: Journal[] = []
afterEach(() => { while (journals.length) journals.pop()!.db.close() })
function service() {
  const journal = new Journal(':memory:')
  journals.push(journal)
  const questions = new QuestionService(journal)
  questions.activatePublicOwner()
  return { journal, questions }
}
function protocol(callback?: ConstructorParameters<typeof CodexClient>[2]) {
  const events: unknown[] = []
  const sent: unknown[] = []
  const client = new CodexClient('unused', (kind, payload) => events.push({ kind, payload }), callback)
  const seam = client as unknown as { send(value: unknown): void; onLine(value: string): void }
  seam.send = value => { sent.push(value) }
  return { events, sent, ingest: (value: unknown) => seam.onLine(JSON.stringify(value)) }
}

describe('Codex questions, distinct from Claude questions and tool permissions', () => {
  it('keys answers by stable id, supports free text and preserves secret bytes without persisting them', async () => {
    const { journal, questions } = service()
    const events: unknown[] = []
    journal.on('event', event => events.push(event))
    const pending = answerCodexQuestion('s1', input, { requestId: 'rpc-1', signal: new AbortController().signal }, {
      request: request => questions.request(request), abort: (id, sid) => questions.abort(id, sid),
    })
    const record = questions.pending()[0]!
    expect(record).toMatchObject({ provider: 'codex', blocking: false })
    expect(record.questions[1]).toMatchObject({ id: 'secret', allowFreeText: true, isSecret: true })
    expect(() => questions.answer(record.id, { mode: 'invented', secret: 'value' })).toThrow(/offered choices/)
    questions.answer(record.id, { mode: 'Quick', secret: '  private value  ' })
    await expect(pending).resolves.toEqual({ answers: { mode: { answers: ['Quick'] }, secret: { answers: ['  private value  '] } } })
    expect(JSON.stringify(events)).not.toContain('private value')
    expect(JSON.stringify(events)).not.toContain('Choose an answer')
    expect(() => parseAskUserQuestionInput(input)).toThrow()
  })

  it('fails closed on duplicate ids, oversized or missing contracts, wrong keys and missing attribution', async () => {
    const normalized = parseCodexQuestionInput(input)
    expect(() => parseQuestionAnswers(normalized.questions, { 'Choose an answer': 'Quick' })).toThrow()
    expect(() => parseCodexQuestionInput({ ...input, questions: [input.questions[0], input.questions[0]] })).toThrow(/Duplicate/)
    expect(() => parseCodexQuestionInput({ ...input, isBlocking: undefined })).toThrow(/blocking/)
    expect(() => parseCodexQuestionInput({ ...input, questions: Array(9).fill(input.questions[0]) })).toThrow()
    const request = vi.fn()
    await expect(answerCodexQuestion(undefined, input, undefined, { request, abort: vi.fn() })).resolves.toEqual({ answers: {} })
    expect(request).not.toHaveBeenCalled()
    expect(codexRequestResult('item/tool/requestUserInput', true)).toEqual({ answers: {} })
    expect(codexRequestResult('item/tool/requestUserInput', false)).toEqual({ answers: {} })
  })

  it('keeps nonblocking requests across turn completion and ignores cross-thread cleanup; resolves exactly once', async () => {
    const { questions } = service()
    const { ingest, sent, events } = protocol((method, params, context) =>
      answerCodexQuestion('s1', params, context, { request: q => questions.request(q), abort: (id, sid) => questions.abort(id, sid) }))
    ingest({ id: 'native-1', method: 'item/tool/requestUserInput', params: input })
    await vi.waitFor(() => expect(questions.pending()).toHaveLength(1))
    ingest({ method: 'turn/completed', params: { threadId: 'thread', turn: { status: 'completed' } } })
    ingest({ method: 'serverRequest/resolved', params: { threadId: 'other-thread', requestId: 'native-1' } })
    expect(questions.pending()).toHaveLength(1)
    expect(sent).toHaveLength(0)
    expect(JSON.stringify(events)).not.toContain('Choose an answer')
    questions.answer(questions.pending()[0]!.id, { mode: 'Deep', secret: 'answer' })
    await vi.waitFor(() => expect(sent).toHaveLength(1))
    expect(sent[0]).toEqual({ id: 'native-1', result: { answers: { mode: { answers: ['Deep'] }, secret: { answers: ['answer'] } } } })
    ingest({ method: 'serverRequest/resolved', params: { threadId: 'thread', requestId: 'native-1' } })
    expect(sent).toHaveLength(1)
  })

  it('aborts only the exact resolved request and suppresses any late response, including duplicated ids', async () => {
    const { questions } = service()
    const { ingest, sent } = protocol((_method, params, context) =>
      answerCodexQuestion('s1', params, context, { request: q => questions.request(q), abort: (id, sid) => questions.abort(id, sid) }))
    ingest({ id: 1, method: 'item/tool/requestUserInput', params: input })
    ingest({ id: 1, method: 'item/tool/requestUserInput', params: { ...input, itemId: 'wrong' } })
    ingest({ id: 2, method: 'item/tool/requestUserInput', params: { ...input, itemId: 'second' } })
    await vi.waitFor(() => expect(questions.pending()).toHaveLength(2))
    const first = questions.pending()[0]!.id
    ingest({ method: 'serverRequest/resolved', params: { threadId: 'thread', requestId: 1 } })
    await vi.waitFor(() => expect(questions.pending()).toHaveLength(1))
    expect(questions.answer(first, { mode: 'Quick', secret: 'late' })).toBe(false)
    questions.cancel(questions.pending()[0]!.id)
    await vi.waitFor(() => expect(sent).toEqual([{ id: 2, result: { answers: {} } }]))
  })

  it('does not conflate string and numeric JSON-RPC ids or accept malformed params', async () => {
    const { questions } = service()
    const { ingest, sent } = protocol((_method, params, context) =>
      answerCodexQuestion('s1', params, context, { request: q => questions.request(q), abort: (id, sid) => questions.abort(id, sid) }))
    ingest({ id: 1, method: 'item/tool/requestUserInput', params: input })
    ingest({ id: '1', method: 'item/tool/requestUserInput', params: input })
    ingest({ id: 2, method: 'item/tool/requestUserInput', params: null })
    await vi.waitFor(() => expect(questions.pending()).toHaveLength(2))
    await vi.waitFor(() => expect(sent).toEqual([{ id: 2, result: { answers: {} } }]))
    for (const record of questions.pending()) questions.cancel(record.id)
    await vi.waitFor(() => expect(sent).toHaveLength(3))
    expect(sent).toContainEqual({ id: 1, result: { answers: {} } })
    expect(sent).toContainEqual({ id: '1', result: { answers: {} } })
  })

  it.each(['in-process', 'worker'] as const)('routes %s requests to questions, never approvals', async mode => {
    const { questions } = service()
    const approvals = { requestDetailed: vi.fn() }
    const signal = new AbortController()
    let ask: (method: string, params: unknown, context: CodexQuestionContext) => Promise<unknown>
    if (mode === 'worker') {
      const worker = new AgentWorker('unused')
      const seam = worker as unknown as {
        codexThreads: Map<string, string>; codexApproval: typeof ask;
        relayRpc(method: string, args: Record<string, unknown>): Promise<unknown>
      }
      seam.codexThreads.set('s1', 'thread')
      seam.relayRpc = async (method, args) => {
        if (method === 'questions.request') return questions.request(args as never)
        if (method === 'questions.abort') return questions.abort(String(args.id), String(args.sessionId))
        throw new Error(`Unexpected relay ${method}`)
      }
      ask = seam.codexApproval.bind(worker)
    } else {
      const executor = new InProcessExecutor({ questions, approvals } as never)
      executor.bindHub({ journal: vi.fn() } as never)
      const seam = executor as unknown as {
        codexThreads: Map<string, string>; codexClientFor(profileId: string, profileDir: string): CodexClient;
      }
      seam.codexThreads.set('s1', 'thread')
      const client = seam.codexClientFor('p1', 'unused')
      ask = (client as unknown as { onApproval: typeof ask }).onApproval
    }
    const pending = ask('item/tool/requestUserInput', input, { requestId: 'rpc', signal: signal.signal })
    expect(questions.pending()).toHaveLength(1)
    signal.abort()
    await expect(pending).resolves.toEqual({ answers: {} })
    expect(questions.pending()).toHaveLength(0)
    expect(approvals.requestDetailed).not.toHaveBeenCalled()
  })
})
