#!/bin/bash
# Install AllMyAgents on macOS, with no Apple Developer ID and no Gatekeeper fight.
#
#   curl -fsSL https://raw.githubusercontent.com/nathanfraske/AllMyAgents/main/scripts/install-macos.sh | bash
#
# WHY THIS EXISTS, and why it is not a hack.
#
# Gatekeeper does not check every app — it checks QUARANTINED apps. The `com.apple.quarantine`
# extended attribute is written by the program that did the downloading (Safari, Chrome, Mail…), not
# by macOS itself. curl does not write it. An app that was never quarantined is never shown to
# Gatekeeper, so it opens normally even though it is unsigned.
#
# That is the whole trick. There is no signature to forge, nothing disabled system-wide, and no
# security setting changed: this narrowly avoids marking OUR OWN download as untrusted-from-the-web.
# Compare the alternative we used to document — download in a browser, then `xattr -dr` the flag off
# afterwards — which reaches the identical end state with more steps and more room to get it wrong.
#
# WHAT THIS DOES NOT DO. It does not make the app notarized, and it does not make it safe by virtue of
# having run. macOS is no longer vouching for this binary; you are, because you know where it came
# from. If you did not get this URL from the AllMyAgents repo, stop. Proper notarization needs a paid
# Apple Developer ID — see docs/alpha-cut-checklist.md.
#
# Reading a script before piping it to a shell is a good habit; this one is deliberately short enough
# to do that. To install without piping:
#   curl -fsSLO https://raw.githubusercontent.com/nathanfraske/AllMyAgents/main/scripts/install-macos.sh
#   less install-macos.sh && bash install-macos.sh
#
# It also puts an `allmyagents` command on your PATH so the app can be started from a terminal, and
# `--uninstall` takes both back off again. See usage() below.
#
# BASH 3.2 IS THE TARGET. `curl | bash` runs whatever `bash` is first on PATH, and on a stock Mac that
# is /bin/bash 3.2.57 from 2007. CI is not that: GitHub's macOS runners have a Homebrew bash 5 earlier
# on PATH, so a 3.2-only failure passes there and breaks on every real user's machine. Nothing below
# may use bash 4 syntax (no ${x,,}, no associative arrays, no mapfile, no [[ -v ]]).

set -euo pipefail

REPO="${AMA_REPO:-nathanfraske/AllMyAgents}"
APP="AllMyAgents.app"
DEST_DIR="${AMA_DEST:-/Applications}"
CMD="allmyagents"

# How the installer recognises its own past work. Both strings are matched literally (grep -F, awk ==)
# when re-running or uninstalling, so that we never append a duplicate and never delete a file or a
# shell-rc line somebody else wrote. Changing either string orphans the previous one.
RC_MARKER="# added by the AllMyAgents installer"
LAUNCHER_MARKER="generated by the AllMyAgents installer"

die() { printf '\n\033[31merror:\033[0m %s\n' "$1" >&2; exit 1; }
say() { printf '\033[36m==>\033[0m %s\n' "$1"; }

usage() {
  cat <<'USAGE'
Install AllMyAgents on macOS and put an `allmyagents` command on your PATH.

  curl -fsSL https://raw.githubusercontent.com/nathanfraske/AllMyAgents/main/scripts/install-macos.sh | bash

Options:
  --add-to-path   Add the launcher's directory to your shell rc without asking.
  --no-path       Install the app only. No launcher, no PATH changes.
  --uninstall     Remove the app, the launcher, and the PATH line this installer added.
  --purge-data    With --uninstall, also permanently remove chats, settings, and vendor logins.
  -y, --yes       Answer yes to prompts. Useful for non-interactive automation.
  -h, --help      This text.

Environment:
  AMA_TAG         Install a specific release tag instead of the latest.
  AMA_DEST        Install the .app somewhere other than /Applications.
  AMA_BIN_DIR     Put the launcher somewhere other than the default (see below).
  AMA_REPO        owner/name to install from. For testing forks.
  GITHUB_TOKEN    Optional. Raises GitHub's 60-requests/hour anonymous API limit.

Re-running is safe: it replaces the app and rewrites the launcher, and it will not add a
second copy of the PATH line.
USAGE
}

DO_UNINSTALL=0
PURGE_DATA=0
PATH_MODE="ask"
ASSUME_YES=0
while [ $# -gt 0 ]; do
  case "$1" in
    --uninstall) DO_UNINSTALL=1 ;;
    --purge-data) PURGE_DATA=1 ;;
    --add-to-path) PATH_MODE="yes" ;;
    --no-path) PATH_MODE="no" ;;
    -y|--yes) ASSUME_YES=1 ;;
    -h|--help) usage; exit 0 ;;
    *) usage >&2; die "unknown option '$1'" ;;
  esac
  shift
done
[ "$PURGE_DATA" = 0 ] || [ "$DO_UNINSTALL" = 1 ] || die "--purge-data must be used with --uninstall"

[ "$(uname -s)" = "Darwin" ] || die "this installer is for macOS. On Windows use scripts/install-windows.ps1, on Linux build from source."

# Asking a question from inside `curl ... | bash` is a trap: the script's own remaining text IS stdin,
# so `read` swallows the next few lines of the installer instead of getting an answer, and the script
# then dies somewhere unrelated. Read from the controlling terminal instead, and when there is not one
# say which flag to pass rather than hanging or assuming consent.
confirm() {
  [ "$ASSUME_YES" = 1 ] && return 0
  [ -r /dev/tty ] || return 1
  printf '%s [y/N] ' "$1" > /dev/tty
  REPLY_LINE=""
  read -r REPLY_LINE < /dev/tty || return 1
  case "$REPLY_LINE" in
    y|Y|yes|YES|Yes) return 0 ;;
    *) return 1 ;;
  esac
}

# WHERE THE LAUNCHER GOES, and why it is not any of the other three candidates.
#
# /usr/local/bin is listed in /etc/paths, so anything placed there is on PATH in every shell, GUI
# terminal included, with no follow-up from the user. That is the best outcome by a distance -- but
# only when it ALREADY EXISTS and we can write it without sudo. On an Apple Silicon Mac that never had
# Homebrew it does not exist at all, and creating it means `sudo mkdir` + a root-owned /usr/local,
# which is precisely the state Homebrew's FAQ spends its length undoing. Not worth it for a shim.
#
# /opt/homebrew/bin is Homebrew's namespace. It only exists if Homebrew does, and dropping a file in
# there that no formula owns makes `brew doctor` complain and risks being cleaned up under us.
#
# ~/.local/bin is the fallback: no sudo ever, creatable on any machine, and conventional. Its one flaw
# is that macOS does not put it on PATH, which is exactly why path_setup() below prints the literal
# line to add instead of assuming the launcher can be found.
choose_bin_dir() {
  if [ -n "${AMA_BIN_DIR:-}" ]; then printf '%s' "$AMA_BIN_DIR"; return; fi
  if [ -d /usr/local/bin ] && [ -w /usr/local/bin ]; then printf '%s' "/usr/local/bin"; return; fi
  printf '%s' "$HOME/.local/bin"
}

write_launcher() {
  BIN_DIR="$(choose_bin_dir)"
  mkdir -p "$BIN_DIR" || die "could not create $BIN_DIR for the allmyagents command"
  LAUNCHER="$BIN_DIR/$CMD"

  # The app path is interpolated at install time; everything after it is a quoted heredoc so that $@,
  # $1 and friends survive into the generated file instead of being expanded here. %q quotes the path
  # for us, which matters because AMA_DEST is user-supplied.
  {
    printf '#!/bin/bash\n'
    printf '# %s -- do not edit; re-running the installer overwrites this file.\n' "$LAUNCHER_MARKER"
    printf 'APP=%q\n' "$DEST_DIR/$APP"
    cat <<'LAUNCHER'
set -euo pipefail

usage() {
  cat <<'INNER'
allmyagents - start the AllMyAgents desktop app.

  allmyagents              Start the app (or bring it to the front if it is already running).
  allmyagents --version    Print the installed version.
  allmyagents --foreground Run attached to this terminal, with the app's output here.

Anything else is passed through to the app.
INNER
}

# --help before the exists check, deliberately: asking a broken command what it does is exactly when
# you need it to answer. Everything below reads the bundle, so it comes after.
case "${1:-}" in
  -h|--help) usage; exit 0 ;;
esac

if [ ! -d "$APP" ]; then
  printf 'allmyagents: %s is not there any more.\n' "$APP" >&2
  printf 'Reinstall with: curl -fsSL https://raw.githubusercontent.com/nathanfraske/AllMyAgents/main/scripts/install-macos.sh | bash\n' >&2
  exit 1
fi

case "${1:-}" in
  -V|--version)
    exec /usr/libexec/PlistBuddy -c 'Print :CFBundleShortVersionString' "$APP/Contents/Info.plist" ;;
  -f|--foreground)
    shift
    # A DEBUGGING MODE, and not how the app normally starts. Launched from a terminal the app inherits
    # this shell's PATH; launched from Finder it inherits launchd's, which is far smaller. A hub that
    # only spawns under the first one is a shipped bug that looks fine here -- that asymmetry is the
    # entire reason .github/workflows/clean-machine-install.yml exists. Do not use this run to
    # conclude the app works.
    #
    # The executable inside the bundle is named for the CRATE (allmyagents-desktop), not for
    # productName, because tauri.conf.json sets no mainBinaryName. Read CFBundleExecutable rather than
    # guessing: guessing that name has cost this repo three separate bugs.
    EXE="$(/usr/libexec/PlistBuddy -c 'Print :CFBundleExecutable' "$APP/Contents/Info.plist")"
    exec "$APP/Contents/MacOS/$EXE" "$@" ;;
esac

# `open -a APP file...` treats trailing arguments as FILES to open; --args is what forwards them to
# the program. Passing none at all is the common case and needs neither.
if [ "$#" -gt 0 ]; then
  exec /usr/bin/open -a "$APP" --args "$@"
fi
exec /usr/bin/open -a "$APP"
LAUNCHER
  } > "$LAUNCHER" || die "could not write $LAUNCHER"
  chmod +x "$LAUNCHER" || die "could not make $LAUNCHER executable"
  say "Installed the 'allmyagents' command to $LAUNCHER"
}

rc_file_and_line() {
  # $SHELL is the login shell, which is what a new terminal window will start.
  case "$(basename "${SHELL:-/bin/zsh}")" in
    zsh)  RC="$HOME/.zshrc" ;;
    # NOT ~/.bashrc. Terminal.app starts bash as a LOGIN shell, which reads ~/.bash_profile and never
    # reads ~/.bashrc unless that file sources it. "I added the line and it still does not work" is
    # almost always this.
    bash) RC="$HOME/.bash_profile" ;;
    fish) RC="$HOME/.config/fish/config.fish" ;;
    *)    RC="$HOME/.profile" ;;
  esac
  case "$RC" in
    *config.fish) RC_LINE="fish_add_path $BIN_DIR" ;;
    *) RC_LINE="export PATH=\"$BIN_DIR:\$PATH\"" ;;
  esac
}

add_rc_line() {
  mkdir -p "$(dirname "$RC")" || die "could not create $(dirname "$RC")"
  [ -f "$RC" ] || : > "$RC"
  # Two independent guards so a second run cannot append a second copy: our own marker, and the
  # directory itself in case the user already added it in some other form.
  if grep -qF "$RC_MARKER" "$RC" 2>/dev/null || grep -qF "$BIN_DIR" "$RC" 2>/dev/null; then
    say "$RC already puts $BIN_DIR on PATH -- left it alone."
    return
  fi
  printf '\n%s\n%s\n' "$RC_MARKER" "$RC_LINE" >> "$RC" || die "could not write to $RC"
  say "Added it to $RC."
  echo "That takes effect in NEW terminals. For this one, run:  $RC_LINE"
}

remove_rc_line() {
  [ -f "$RC" ] || return 0
  grep -qF "$RC_MARKER" "$RC" 2>/dev/null || return 0
  cp "$RC" "$RC.allmyagents.bak" || die "could not back up $RC"
  # Remove EXACTLY what add_rc_line wrote: the blank separator, the marker, and the one line after it.
  #
  # The blank line matters. add_rc_line leads with \n so that appending to a file whose last line has
  # no terminating newline cannot glue the marker onto it -- but a removal that drops only two of the
  # three lines leaves one blank behind every time, and install/uninstall/install then walks the rc
  # file down the page. Buffering lets us un-write the blank only when it is genuinely ours (n>0 and
  # the held line is empty), so a marker that happens to sit at the top of the file loses nothing.
  #
  # Written to a temp first: a failing awk must not be able to leave someone with a truncated shell rc.
  awk -v m="$RC_MARKER" '
    skip { skip=0; next }
    $0 == m { skip=1; if (n > 0 && buf[n] == "") n--; next }
    { buf[++n] = $0 }
    END { for (i = 1; i <= n; i++) print buf[i] }
  ' "$RC.allmyagents.bak" > "$RC.allmyagents.tmp" && mv "$RC.allmyagents.tmp" "$RC" \
    || die "could not rewrite $RC. Your original is at $RC.allmyagents.bak -- remove the two lines under '$RC_MARKER' by hand."
  say "Removed the PATH line from $RC (backup: $RC.allmyagents.bak)"
}

path_setup() {
  case ":${PATH:-}:" in
    *":$BIN_DIR:"*)
      say "$BIN_DIR is already on your PATH -- 'allmyagents' works in a new terminal."
      return ;;
  esac

  rc_file_and_line
  echo
  echo "$BIN_DIR is NOT on your PATH, so typing 'allmyagents' will not find it yet."
  echo "Add this line to $RC:"
  echo
  echo "    $RC_LINE"
  echo

  [ "$PATH_MODE" = "no" ] && return 0
  if [ "$PATH_MODE" = "yes" ]; then
    add_rc_line
  elif confirm "Add it for you?"; then
    add_rc_line
  else
    echo "Left your shell config alone. Until you add that line, start the app with:"
    echo "    $LAUNCHER"
  fi
}

do_uninstall() {
  echo "This will remove:"
  [ -e "$DEST_DIR/$APP" ] && echo "  $DEST_DIR/$APP"
  echo "  the 'allmyagents' launcher, if this installer wrote it"
  echo "  the PATH line this installer added to your shell config"
  echo
  if [ "$PURGE_DATA" = 1 ]; then
    echo "It WILL permanently remove chats, settings, worktrees, and saved Claude/Codex logins."
  else
    echo "It will KEEP your chats, settings, worktrees, and saved Claude/Codex logins."
  fi
  if ! confirm "Continue?"; then
    die "cancelled, nothing was removed. Pass --yes to skip this question."
  fi

  # Only ever delete a launcher we generated. A file called `allmyagents` that we did not write
  # belongs to somebody else, and an uninstaller that removes it is worse than one that leaves litter.
  for d in "${AMA_BIN_DIR:-}" /usr/local/bin "$HOME/.local/bin" /opt/homebrew/bin; do
    [ -n "$d" ] || continue
    [ -f "$d/$CMD" ] || continue
    if grep -qF "$LAUNCHER_MARKER" "$d/$CMD" 2>/dev/null; then
      rm -f "$d/$CMD" && say "Removed $d/$CMD"
    else
      say "Left $d/$CMD alone -- it has no installer marker in it, so it is not ours."
    fi
  done

  BIN_DIR="$(choose_bin_dir)"
  rc_file_and_line
  remove_rc_line

  if [ -e "$DEST_DIR/$APP" ]; then
    rm -rf "$DEST_DIR/$APP" 2>/dev/null || sudo rm -rf "$DEST_DIR/$APP" || die "could not remove $DEST_DIR/$APP"
    say "Removed $DEST_DIR/$APP"
  fi

  HUB_HOME="$HOME/Library/Application Support/direct.cec.allmyagents"
  if [ -e "$HUB_HOME" ]; then
    rm -rf "$HUB_HOME" || die "could not remove the regenerable hub files at $HUB_HOME"
    say "Removed regenerable hub files at $HUB_HOME"
  fi

  USER_DATA="$HOME/Library/Application Support/AllMyAgents"
  if [ "$PURGE_DATA" = 1 ] && [ -e "$USER_DATA" ]; then
    rm -rf "$USER_DATA" || die "could not remove operator data at $USER_DATA"
    say "Removed chats, settings, worktrees, and saved vendor logins at $USER_DATA"
  fi

  printf '\n\033[32mOK\033[0m AllMyAgents removed.\n\n'
  if [ "$PURGE_DATA" = 1 ]; then
    echo "The app, regenerable hub, chats, settings, and saved vendor credentials were removed."
  else
    echo "Your chats, settings, worktrees, and saved Claude/Codex logins are still on disk, deliberately:"
    echo "    ~/Library/Application Support/AllMyAgents"
    echo "To delete them too, rerun with: --uninstall --purge-data"
  fi
  exit 0
}

[ "$DO_UNINSTALL" = 1 ] && do_uninstall

# Which build. Tauri names the artifacts _aarch64 (Apple Silicon) and _x64 (Intel).
case "$(uname -m)" in
  arm64) ARCH="aarch64"; ARCH_LABEL="Apple Silicon" ;;
  x86_64) ARCH="x64"; ARCH_LABEL="Intel" ;;
  *) die "unrecognised architecture '$(uname -m)'" ;;
esac
say "Mac architecture: $ARCH_LABEL ($ARCH)"

TAG="${AMA_TAG:-}"
API="https://api.github.com/repos/${REPO}/releases/latest"
[ -n "$TAG" ] && API="https://api.github.com/repos/${REPO}/releases/tags/${TAG}"

say "Looking up the ${TAG:-latest} release..."
# Capture the STATUS, because "it failed" and "you are offline" are not the same thing. This said
# "Are you online?" for every failure, and the first one CI actually hit was a 403 rate limit — telling
# a perfectly connected machine its network was broken. Anyone behind corporate NAT, a university, or a
# VPN shares an IP and can hit the same unauthenticated limit of 60 requests/hour.
# GITHUB_TOKEN, if present, raises that limit; it is optional and never required.
#
# The ${AUTH[@]+...} wrapper is not decoration. Before bash 4.4, expanding an EMPTY array as
# "${AUTH[@]}" under `set -u` is an "unbound variable" error, and bash 3.2 is what a stock Mac runs.
# Without a GITHUB_TOKEN in the environment -- i.e. the normal case for every real user -- this line
# left AUTH empty and the curl below aborted the installer before it downloaded anything. CI never saw
# it: the runners have a Homebrew bash 5 ahead of /bin/bash on PATH, and CI also sets GITHUB_TOKEN.
AUTH=()
[ -n "${GITHUB_TOKEN:-}" ] && AUTH=(-H "Authorization: Bearer ${GITHUB_TOKEN}")
# NOTE: a second `trap ... EXIT` below REPLACES this one rather than adding to it, so the later trap
# cleans up both. Bash has one EXIT trap, and assuming otherwise silently leaks the first target.
HTTP_BODY="$(mktemp)"
trap 'rm -f "$HTTP_BODY"' EXIT
CODE="$(curl -sSL ${AUTH[@]+"${AUTH[@]}"} -o "$HTTP_BODY" -w '%{http_code}' "$API" 2>/dev/null || echo 000)"
case "$CODE" in
  200) RELEASE_JSON="$(cat "$HTTP_BODY")" ;;
  403|429)
    die "GitHub rate-limited this machine (HTTP $CODE). This is not a connection problem -- the limit is
per IP address and resets within the hour, so a shared or VPN'd network can hit it. Wait a few minutes and
try again, or set GITHUB_TOKEN to a personal access token to raise the limit." ;;
  404) die "no release named '${TAG}' exists in ${REPO}." ;;
  000) die "could not reach github.com at all. Check your internet connection." ;;
  *) die "GitHub returned HTTP $CODE looking up the release." ;;
esac

VERSION="$(printf '%s' "$RELEASE_JSON" | /usr/bin/python3 -c 'import json,sys; print(json.load(sys.stdin).get("tag_name",""))')"
# Match this Mac's architecture exactly. Installing an arm64 build on an Intel Mac produces
# "you can't open the application because it is not supported on this type of Mac", which looks like
# a broken app rather than the wrong download — so refuse rather than guess.
URL="$(printf '%s' "$RELEASE_JSON" | ARCH="$ARCH" /usr/bin/python3 -c '
import json, os, sys
arch = os.environ["ARCH"]
assets = json.load(sys.stdin).get("assets", [])
for a in assets:
    n = a.get("name", "")
    if n.endswith(".dmg") and ("_%s.dmg" % arch) in n:
        print(a["browser_download_url"]); break
')"
[ -n "$URL" ] || die "release ${VERSION:-latest} has no .dmg for $ARCH_LABEL ($ARCH). Ask for an ${ARCH} build to be published."

say "Downloading $VERSION for $ARCH_LABEL..."
TMP="$(mktemp -d)"
# shellcheck disable=SC2064
trap "rm -rf '$TMP' '$HTTP_BODY'; hdiutil detach '$TMP/mnt' >/dev/null 2>&1 || true" EXIT
DMG="$TMP/AllMyAgents.dmg"
# THE LOAD-BEARING LINE. curl does not set com.apple.quarantine, so what lands here is never flagged
# as web-downloaded and Gatekeeper is never consulted for it. Downloading this same file in a browser
# instead is what produces "AllMyAgents is damaged and can't be opened".
curl -fL --progress-bar -o "$DMG" "$URL" || die "download failed"

say "Mounting..."
mkdir -p "$TMP/mnt"
hdiutil attach "$DMG" -nobrowse -readonly -mountpoint "$TMP/mnt" >/dev/null || die "could not mount the disk image"
[ -d "$TMP/mnt/$APP" ] || die "the disk image does not contain $APP"

if [ -e "$DEST_DIR/$APP" ]; then
  say "Replacing the existing $DEST_DIR/$APP..."
  rm -rf "$DEST_DIR/$APP" 2>/dev/null || sudo rm -rf "$DEST_DIR/$APP" || die "could not remove the old install"
fi

say "Installing to $DEST_DIR..."
USED_SUDO=0
if ! cp -R "$TMP/mnt/$APP" "$DEST_DIR/" 2>/dev/null; then
  sudo cp -R "$TMP/mnt/$APP" "$DEST_DIR/" || die "could not copy into $DEST_DIR"
  USED_SUDO=1
fi
hdiutil detach "$TMP/mnt" >/dev/null 2>&1 || true

# THE APP MUST BE OWNED BY THE USER WHO WILL RUN IT, or auto-update silently stops working.
#
# On macOS the Tauri updater replaces the .app bundle in place, running as the logged-in user. A
# root-owned bundle — which is exactly what `sudo cp` above leaves behind — cannot be written by that
# user, so every future update fails. The app keeps offering the update and it keeps not applying,
# which is a far worse failure than a noisy one: it looks like the updater is broken rather than the
# permissions. /Applications is group-writable by admins, so the sudo path is rare, but "rare" here
# means "one tester whose updates mysteriously never stick".
if [ "$USED_SUDO" = 1 ]; then
  sudo chown -R "$(id -u):$(id -g)" "$DEST_DIR/$APP" || die "installed, but could not hand ownership back to you -- auto-update would fail"
fi
[ -w "$DEST_DIR/$APP" ] || die "installed, but $DEST_DIR/$APP is not writable by you -- auto-update would fail"

# Belt and braces. Nothing above should have set the flag, but a previous BROWSER download of the same
# app can leave a quarantined copy behind, and on some setups the attribute is inherited rather than
# freshly applied. Clearing it costs nothing and removes the one failure mode this script exists to
# prevent. `|| true` because there is normally no attribute to remove and that is not an error.
xattr -dr com.apple.quarantine "$DEST_DIR/$APP" 2>/dev/null || true

if xattr -p com.apple.quarantine "$DEST_DIR/$APP" >/dev/null 2>&1; then
  die "the app is still quarantined -- Gatekeeper will block it. Run: xattr -dr com.apple.quarantine '$DEST_DIR/$APP'"
fi

# The embedded Node runtime is what the hub actually runs on. If it cannot execute, the app launches
# to a window that never connects — which is a much more confusing failure than not installing at all.
NODE="$DEST_DIR/$APP/Contents/Resources/hub-runtime/node/node"
[ -x "$NODE" ] || die "the bundled Node runtime is missing or not executable at $NODE -- refusing to leave a dead-window install"
"$NODE" --version >/dev/null 2>&1 || die "the bundled Node runtime will not execute -- refusing to leave a dead-window install"

printf '\n\033[32mOK\033[0m Installed %s to %s\n\n' "${VERSION:-AllMyAgents}" "$DEST_DIR/$APP"

if [ "$PATH_MODE" = "no" ]; then
  echo "Skipped the 'allmyagents' command (--no-path)."
  echo "Open it from Applications, or run:  open '$DEST_DIR/$APP'"
else
  write_launcher
  path_setup
  echo
  echo "Start it from Applications, by typing 'allmyagents', or with:  open '$DEST_DIR/$APP'"
fi

echo
echo "First launch needs an internet connection -- it fetches the hub's dependencies and the vendor"
echo "CLIs from npm, which takes a couple of minutes. The window says so while it works."
echo
echo "To uninstall later (keeping chats and logins):"
echo "  curl -fsSL https://raw.githubusercontent.com/nathanfraske/AllMyAgents/main/scripts/install-macos.sh | bash -s -- --uninstall"
