<#
    Install AllMyAgents on Windows from a terminal, and put an `allmyagents` command on the PATH.

      irm https://raw.githubusercontent.com/nathanfraske/AllMyAgents/main/scripts/install-windows.ps1 | iex

    To pass options through that one-liner, `iex` is not enough -- it evaluates a string and has
    nowhere to put arguments. Build a scriptblock instead:

      & ([scriptblock]::Create((irm https://raw.githubusercontent.com/nathanfraske/AllMyAgents/main/scripts/install-windows.ps1))) -Uninstall

    Or, better, keep the file so you can read it before running it and re-run it later:

      irm https://raw.githubusercontent.com/nathanfraske/AllMyAgents/main/scripts/install-windows.ps1 -OutFile install-allmyagents.ps1
      notepad install-allmyagents.ps1
      .\install-allmyagents.ps1

    WHY THE DEFAULT IS THE -setup.exe AND NOT THE .msi.

    The MSI is a PER-MACHINE package. Read straight out of its Property table: ALLUSERS=1, and
    INSTALLDIR's parent in the Directory table is ProgramFiles64Folder. A per-machine install into
    Program Files needs administrator rights, and `msiexec /qn` cannot show a UAC prompt -- it just
    fails, from a shell the user opened normally. So the MSI cannot be the default for an installer
    whose whole selling point is that it needs no elevation.

    The NSIS -setup.exe is built with installMode: currentUser (see tauri.conf.json), lands in
    %LOCALAPPDATA%\AllMyAgents, and needs no elevation at all. It is also what the alpha testers
    already have installed. That is the default here; -Msi opts into the other one and says plainly
    that you need an elevated shell for it.

    WHAT IT DOES NOT DO. The build has no Authenticode certificate, so SmartScreen warns on first
    launch and this script cannot verify a publisher signature. It checks what it can -- the exact
    byte count GitHub reported for the asset, and the file's magic bytes -- and prints the SHA-256 so
    you can compare it against the release page. If you did not get this URL from the AllMyAgents
    repo, stop.

    Re-running is safe. It skips the download when the same version is already installed, rewrites
    the shim unconditionally, and will not add a second copy of the PATH entry.
#>

[CmdletBinding()]
param(
    # Defaults come from the environment as well as the parameter list, because the `irm | iex`
    # one-liner above can set environment variables and cannot set parameters.
    [string]$Tag    = $env:AMA_TAG,
    [string]$Repo   = $(if ($env:AMA_REPO) { $env:AMA_REPO } else { 'nathanfraske/AllMyAgents' }),
    [string]$BinDir = $env:AMA_BIN_DIR,

    [switch]$Msi,
    [switch]$Uninstall,
    [switch]$KeepApp,
    [switch]$PathOnly,
    [switch]$NoPath,
    [switch]$Force,
    [switch]$Help
)

$ErrorActionPreference = 'Stop'

# Invoke-WebRequest in Windows PowerShell renders a progress bar per chunk, and on a 28 MB download
# that rendering costs more wall-clock time than the transfer. Turning it off is worth roughly 10x.
$ProgressPreference = 'SilentlyContinue'

# Windows PowerShell picks its TLS versions from a machine-wide default that on older or hardened
# boxes still excludes TLS 1.2, which is the only thing github.com accepts. The resulting error is
# "The request was aborted: Could not create SSL/TLS secure channel" -- which reads like a broken
# network rather than a protocol default, and sends people to the wrong place entirely.
[Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12

$AppName  = 'AllMyAgents'
$CmdName  = 'allmyagents'

# THE INSTALLED BINARY IS NAMED FOR THE CRATE, NOT FOR productName. tauri.conf.json sets no
# mainBinaryName, so the bundler uses the Cargo package name (allmyagents-desktop). Verified three
# ways before this file was written: the crate name in apps/desktop/src-tauri/Cargo.toml, the File
# table of a locally built MSI, and the actual file on disk in an existing install. Assuming
# "AllMyAgents.exe" has now caused two separate bugs in this repo, so it is written down here.
$ExeName  = 'allmyagents-desktop.exe'
$ProcName = 'allmyagents-desktop'

# How the installer recognises its own past work, so that re-running never duplicates anything and
# uninstalling never deletes a file somebody else put there.
$ShimMarker = 'generated by the AllMyAgents installer'

if (-not $BinDir) { $BinDir = Join-Path $env:LOCALAPPDATA 'AllMyAgents\bin' }
$ShimPath = Join-Path $BinDir "$CmdName.cmd"

# `exit` is what makes a CI step fail, and this script must not swallow that. But under
# `irm ... | iex` there is no script to exit from, so `exit` would close the user's PowerShell window
# over something as ordinary as a rate limit. $PSCommandPath is set only when running from a file.
$FromFile = [bool]$PSCommandPath

function Say  { param([string]$m) Write-Host "==> $m" -ForegroundColor Cyan }
function Note { param([string]$m) Write-Host "    $m" }
function Warn { param([string]$m) Write-Host "warning: $m" -ForegroundColor Yellow }
function Die {
    param([string]$m)
    Write-Host ''
    Write-Host "error: $m" -ForegroundColor Red
    if ($FromFile) { exit 1 } else { throw $m }
}

function Show-Usage {
    Write-Host @'
Install AllMyAgents on Windows and put an `allmyagents` command on your PATH.

  .\install-windows.ps1                Install the latest release (no elevation needed).
  .\install-windows.ps1 -Msi           Use the .msi instead. Needs an elevated shell: the MSI is a
                                       per-machine package that installs into Program Files.
  .\install-windows.ps1 -PathOnly      Leave the app alone; just (re)create the allmyagents command.
  .\install-windows.ps1 -NoPath        Install the app only. No command, no PATH change.
  .\install-windows.ps1 -Uninstall     Remove the app, the command, and the PATH entry.
  .\install-windows.ps1 -Uninstall -KeepApp
                                       Remove only the command and the PATH entry.
  .\install-windows.ps1 -Force         Reinstall even if this version is already installed, and
                                       proceed even if the app is running.
  -Tag v0.1.4-alpha.5                  Install a specific release.
  -BinDir C:\path                      Put the allmyagents command somewhere else.

Environment: AMA_TAG, AMA_REPO, AMA_BIN_DIR, GITHUB_TOKEN (optional; raises GitHub's
anonymous API limit of 60 requests/hour).
'@
}

function Test-Elevated {
    $id = [Security.Principal.WindowsIdentity]::GetCurrent()
    $principal = New-Object Security.Principal.WindowsPrincipal($id)
    return $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
}

# ---------------------------------------------------------------------------------------------
# USER PATH
#
# The string handling lives in two pure functions so it can be tested without touching a registry,
# because every bug in this area is a string bug: an entry that differs only by a trailing backslash
# or by case, an empty entry from a stray semicolon, a value appended twice by a second run.
# ---------------------------------------------------------------------------------------------

function Test-PathContains {
    param([string]$RawPath, [string]$Dir)
    $want = $Dir.TrimEnd('\')
    foreach ($p in ($RawPath -split ';')) {
        if ($p -eq '') { continue }
        # Windows paths are case-insensitive and treat a trailing separator as the same directory, so
        # a literal string match would happily add C:\x\bin next to an existing C:\X\bin\.
        if ($p.TrimEnd('\').Equals($want, [StringComparison]::OrdinalIgnoreCase)) { return $true }
    }
    return $false
}

function Add-ToPathString {
    param([string]$RawPath, [string]$Dir)
    if (Test-PathContains -RawPath $RawPath -Dir $Dir) { return $RawPath }
    # Append only. Round-tripping the value through a split/filter/join would also "tidy" things we
    # were never asked to touch -- an empty entry from a double semicolon, ordering, spacing -- and a
    # PATH is not a file to reformat while you are in there.
    if ($RawPath -eq '') { return $Dir }
    if ($RawPath.EndsWith(';')) { return ($RawPath + $Dir) }
    return ($RawPath + ';' + $Dir)
}

function Remove-FromPathString {
    param([string]$RawPath, [string]$Dir)
    $want = $Dir.TrimEnd('\')
    $kept = New-Object System.Collections.ArrayList
    foreach ($p in ($RawPath -split ';')) {
        if ($p -ne '' -and $p.TrimEnd('\').Equals($want, [StringComparison]::OrdinalIgnoreCase)) { continue }
        [void]$kept.Add($p)
    }
    return ($kept -join ';')
}

function Get-UserPath {
    $key = [Microsoft.Win32.Registry]::CurrentUser.OpenSubKey('Environment')
    if (-not $key) { return @{ Value = ''; Kind = 'String' } }
    try {
        if (-not ($key.GetValueNames() -contains 'Path')) { return @{ Value = ''; Kind = 'String' } }
        # DoNotExpandEnvironmentNames is the important part. A user PATH may legitimately contain
        # %USERPROFILE%\bin; reading it the ordinary way hands back the expanded text, and writing
        # that back bakes today's expansion in permanently. The indirection is gone and nobody
        # notices until the variable it depended on changes.
        return @{
            Value = $key.GetValue('Path', '', [Microsoft.Win32.RegistryValueOptions]::DoNotExpandEnvironmentNames)
            Kind  = $key.GetValueKind('Path').ToString()
        }
    } finally { $key.Close() }
}

function Send-EnvironmentChange {
    # A direct registry write changes the stored value but tells nobody. Explorer -- and therefore
    # every program a user starts from it -- keeps the old environment until they sign out.
    # SetEnvironmentVariable broadcasts this message itself; when we have to bypass it (below) we
    # have to send it ourselves.
    if (-not ('Ama.Native' -as [type])) {
        Add-Type -Namespace 'Ama' -Name 'Native' -MemberDefinition @'
[DllImport("user32.dll", SetLastError = true, CharSet = CharSet.Auto)]
public static extern IntPtr SendMessageTimeout(
    IntPtr hWnd, uint Msg, UIntPtr wParam, string lParam,
    uint fuFlags, uint uTimeout, out UIntPtr lpdwResult);
'@
    }
    $result = [UIntPtr]::Zero
    # HWND_BROADCAST, WM_SETTINGCHANGE, SMTO_ABORTIFHUNG, 5s -- a hung top-level window must not be
    # able to wedge an installer.
    [void][Ama.Native]::SendMessageTimeout([IntPtr]0xffff, 0x1A, [UIntPtr]::Zero, 'Environment', 2, 5000, [ref]$result)
}

function Set-UserPath {
    param([string]$Value, [string]$Kind)
    if ($Kind -eq 'ExpandString') {
        # [Environment]::SetEnvironmentVariable writes REG_SZ -- confirmed by experiment on this
        # repo's dev machine, storing "%USERPROFILE%\x" and reading the value kind back as String.
        # Using it on a PATH that is currently REG_EXPAND_SZ therefore converts the type, and every
        # %VAR% entry in it stops expanding from that moment on, for every process on the machine,
        # with no error anywhere. So the documented API is the right tool for the common case and the
        # wrong one here; write it ourselves and send the notification the API would have sent.
        $key = [Microsoft.Win32.Registry]::CurrentUser.OpenSubKey('Environment', $true)
        try { $key.SetValue('Path', $Value, [Microsoft.Win32.RegistryValueKind]::ExpandString) }
        finally { $key.Close() }
        Send-EnvironmentChange
    } else {
        # NEVER $env:Path here. That is the PROCESS environment: the machine PATH, the user PATH and
        # anything this session added, already merged into one string. Writing it back into the User
        # scope copies the whole machine PATH into the user's copy, permanently, and every entry then
        # appears twice in every process started afterwards.
        [Environment]::SetEnvironmentVariable('Path', $Value, 'User')
    }
}

function Add-UserPathEntry {
    param([string]$Dir)
    $cur = Get-UserPath
    if (Test-PathContains -RawPath $cur.Value -Dir $Dir) {
        Say "$Dir is already on your user PATH."
        return
    }
    $new = Add-ToPathString -RawPath $cur.Value -Dir $Dir
    Set-UserPath -Value $new -Kind $cur.Kind

    # Read it back rather than trusting the write. Losing a PATH is expensive to undo by hand, and a
    # silent no-op here would show up much later as "the command does not exist".
    $after = Get-UserPath
    if (-not (Test-PathContains -RawPath $after.Value -Dir $Dir)) {
        Die "wrote the user PATH but $Dir is not in it afterwards. Nothing was lost -- add it yourself via System Properties > Environment Variables."
    }
    Say "Added $Dir to your user PATH (per-user; no administrator rights involved)."
    Note 'Already-open terminals keep the environment they started with -- open a new one.'
}

function Remove-UserPathEntry {
    param([string]$Dir)
    $cur = Get-UserPath
    if (-not (Test-PathContains -RawPath $cur.Value -Dir $Dir)) { return }
    Set-UserPath -Value (Remove-FromPathString -RawPath $cur.Value -Dir $Dir) -Kind $cur.Kind
    Say "Removed $Dir from your user PATH."
}

# ---------------------------------------------------------------------------------------------
# The allmyagents command
# ---------------------------------------------------------------------------------------------

function Write-Shim {
    param([string]$ExePath)
    if (-not (Test-Path -LiteralPath $BinDir)) { New-Item -ItemType Directory -Force -Path $BinDir | Out-Null }

    $lines = @(
        '@echo off'
        "rem $ShimMarker -- do not edit; re-running the installer overwrites this file."
        'rem'
        'rem WHY A SHIM rather than putting the install directory itself on PATH. Two reasons, both'
        'rem practical: the app ships next to its own uninstall.exe, so that directory on PATH would'
        'rem make `uninstall` a global command in every terminal on the machine; and the binary is'
        'rem named for the crate, so the directory would give you `allmyagents-desktop` rather than'
        'rem the name anyone would type. A shim also survives the app moving between the per-user and'
        'rem per-machine layouts without the PATH entry going stale.'
        'setlocal'
        "set `"AMA_EXE=$ExePath`""
        ''
        'rem --help before the exists check, deliberately: asking a broken command what it does is'
        'rem exactly when you need it to answer. --version reads the binary, so it comes after.'
        'if /i "%~1"=="--help"    goto :help'
        'if /i "%~1"=="-h"        goto :help'
        'if /i "%~1"=="/?"        goto :help'
        ''
        'if not exist "%AMA_EXE%" goto :missing'
        ''
        'if /i "%~1"=="--version" goto :version'
        'if /i "%~1"=="-v"        goto :version'
        ''
        'rem The empty "" is the window TITLE argument, not padding. Without it cmd takes the first'
        'rem quoted token as a title, and then opens an empty console window instead of the app.'
        'start "" "%AMA_EXE%" %*'
        'exit /b 0'
        ''
        ':version'
        'rem Full path to powershell.exe: this has to work from a shell with a minimal PATH too.'
        '"%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -NonInteractive -Command "(Get-Item -LiteralPath $env:AMA_EXE).VersionInfo.ProductVersion"'
        'exit /b %errorlevel%'
        ''
        ':help'
        'echo allmyagents - start the AllMyAgents desktop app.'
        'echo.'
        'echo   allmyagents             Start the app.'
        'echo   allmyagents --version   Print the installed version.'
        'echo.'
        'echo Anything else is passed through to the app.'
        'exit /b 0'
        ''
        ':missing'
        'rem Redirect FIRST. `echo text 1>&2` puts the space before the 1 into the output, so every'
        'rem line ends in a stray blank -- cmd takes the redirection off the end, not out of the middle.'
        '>&2 echo allmyagents: %AMA_EXE% is not there any more.'
        '>&2 echo Reinstall, or repair just this command, with:'
        '>&2 echo   irm https://raw.githubusercontent.com/nathanfraske/AllMyAgents/main/scripts/install-windows.ps1 ^| iex'
        'exit /b 1'
    )

    # ASCII, and CRLF. A .cmd file saved as UTF-8 WITH a BOM makes cmd try to run the BOM bytes as
    # part of the first command -- it reports the mojibake back at you and says it is not recognised
    # as a command -- and Set-Content/Out-File are exactly the cmdlets that add one. WriteAllText with
    # an explicit encoding cannot. (This file is kept ASCII-only for the same family of reason:
    # PowerShell 5.1 reads a .ps1 with no BOM as the system ANSI codepage, not UTF-8.)
    [System.IO.File]::WriteAllText($ShimPath, (($lines -join "`r`n") + "`r`n"), [System.Text.Encoding]::ASCII)
    Say "Installed the '$CmdName' command to $ShimPath"
}

function Remove-Shim {
    if (-not (Test-Path -LiteralPath $ShimPath)) { return }
    # Never delete a file we did not write, even when it has our name. An uninstaller that removes
    # somebody else's script is a worse outcome than one that leaves litter behind.
    $text = Get-Content -LiteralPath $ShimPath -Raw -ErrorAction SilentlyContinue
    if ($text -and $text.Contains($ShimMarker)) {
        Remove-Item -LiteralPath $ShimPath -Force
        Say "Removed $ShimPath"
        $left = @(Get-ChildItem -LiteralPath $BinDir -Force -ErrorAction SilentlyContinue)
        if ($left.Count -eq 0) { Remove-Item -LiteralPath $BinDir -Force -ErrorAction SilentlyContinue }
    } else {
        Warn "left $ShimPath alone -- it has no installer marker in it, so it is not ours."
    }
}

# ---------------------------------------------------------------------------------------------
# Finding what is already installed
# ---------------------------------------------------------------------------------------------

function Get-InstalledApp {
    $keys = @(
        'HKCU:\Software\Microsoft\Windows\CurrentVersion\Uninstall\*'
        'HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall\*'
        'HKLM:\Software\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\*'
    )
    $found = Get-ItemProperty -Path $keys -ErrorAction SilentlyContinue |
             Where-Object { $_.DisplayName -eq $AppName } |
             Select-Object -First 1
    if (-not $found) { return $null }

    # NSIS writes InstallLocation WITH literal double quotes around it -- verified on a real install,
    # where the value is "C:\Users\...\AppData\Local\AllMyAgents" quotes included. Join-Path on that
    # produces a path containing a quote character, which then fails Test-Path for reasons that look
    # nothing like the cause.
    $loc = ''
    if ($found.InstallLocation) { $loc = ([string]$found.InstallLocation).Trim('"').TrimEnd('\') }

    # An MSI registers under its ProductCode GUID and uninstalls through msiexec; NSIS registers
    # under a plain name and ships its own uninstall.exe. They need different uninstall commands.
    $kind = 'nsis'
    if ($found.PSChildName -match '^\{[0-9A-Fa-f-]{36}\}$') { $kind = 'msi' }

    return [pscustomobject]@{
        Version         = [string]$found.DisplayVersion
        InstallLocation = $loc
        UninstallString = [string]$found.UninstallString
        ProductCode     = [string]$found.PSChildName
        Kind            = $kind
        Scope           = $(if ($found.PSPath -like '*HKEY_CURRENT_USER*') { 'per-user' } else { 'per-machine' })
    }
}

function Test-SameVersion {
    param([string]$Tag, [string]$Installed)
    if (-not $Installed -or -not $Tag) { return $false }
    # These two never match raw. The git tag carries the pre-release suffix (v0.1.4-alpha.5) while the
    # registry carries the numeric version the bundler used (0.1.4), because MSI/WiX rejects semver
    # pre-release suffixes -- see the comment on `version` in apps/desktop/src-tauri/Cargo.toml. The
    # obvious workaround, a substring wildcard, matches 0.1.1 against 0.1.14 and skips a real upgrade.
    $t = ($Tag -replace '^[vV]', '') -replace '-.*$', ''
    try { return ([version]$t -eq [version]$Installed) } catch { return ($t -eq $Installed) }
}

function Find-Exe {
    param($Installed)
    if ($Installed -and $Installed.InstallLocation) {
        $candidate = Join-Path $Installed.InstallLocation $ExeName
        if (Test-Path -LiteralPath $candidate) { return $candidate }
    }
    $roots = @(
        (Join-Path $env:LOCALAPPDATA $AppName)
        (Join-Path $env:LOCALAPPDATA "Programs\$AppName")
        (Join-Path $env:ProgramFiles $AppName)
    ) | Where-Object { $_ -and (Test-Path -LiteralPath $_) }
    foreach ($r in $roots) {
        $hit = Get-ChildItem -LiteralPath $r -Filter $ExeName -Recurse -ErrorAction SilentlyContinue |
               Select-Object -First 1
        if ($hit) { return $hit.FullName }
    }
    return $null
}

function Assert-NotRunning {
    $running = @(Get-Process -Name $ProcName -ErrorAction SilentlyContinue)
    if ($running.Count -eq 0) { return }
    if ($Force) {
        Warn "$AppName is running; -Force was given, so continuing. The installer may close it."
        return
    }
    Die "$AppName is running (pid $($running[0].Id)). Quit it first, or pass -Force. Installing over a running app can leave a half-replaced install and will interrupt any chat mid-turn."
}

# ---------------------------------------------------------------------------------------------
# Release lookup and download
# ---------------------------------------------------------------------------------------------

function Get-Release {
    $api = "https://api.github.com/repos/$Repo/releases/latest"
    if ($Tag) { $api = "https://api.github.com/repos/$Repo/releases/tags/$Tag" }

    # The GitHub API rejects requests with no User-Agent outright, with a 403 that looks exactly like
    # a rate limit. Send one.
    $headers = @{ 'User-Agent' = 'allmyagents-installer'; 'Accept' = 'application/vnd.github+json' }
    if ($env:GITHUB_TOKEN) { $headers['Authorization'] = "Bearer $env:GITHUB_TOKEN" }

    try {
        return Invoke-RestMethod -Uri $api -Headers $headers -UseBasicParsing -TimeoutSec 30
    } catch {
        # Branch on the STATUS. "it failed" and "you are offline" are not the same thing, and the
        # macOS installer already had to learn this the hard way: it reported every failure as a
        # connection problem, and the first one CI actually hit was a 403 rate limit on a machine
        # with perfect connectivity.
        $code = 0
        if ($_.Exception.PSObject.Properties['Response'] -and $_.Exception.Response) {
            $code = [int]$_.Exception.Response.StatusCode
        }
        if ($code -eq 403 -or $code -eq 429) {
            Die "GitHub rate-limited this machine (HTTP $code). This is not a connection problem -- the limit is 60 requests/hour per IP ADDRESS, so a corporate NAT, a university or a VPN shares it with everyone else on that address. It resets within the hour. Set GITHUB_TOKEN to a personal access token to raise it."
        }
        if ($code -eq 404) { Die "no release named '$Tag' exists in $Repo." }
        if ($code -eq 0)   { Die "could not reach api.github.com at all. Check your internet connection or proxy. ($($_.Exception.Message))" }
        Die "GitHub returned HTTP $code looking up the release."
    }
}

function Select-Asset {
    param($Release)

    # PROCESSOR_ARCHITECTURE reports the architecture of THIS PROCESS, so a 32-bit PowerShell on a
    # 64-bit machine says x86. PROCESSOR_ARCHITEW6432 is set only in that case and holds the real one.
    $arch = $env:PROCESSOR_ARCHITECTURE
    if ($env:PROCESSOR_ARCHITEW6432) { $arch = $env:PROCESSOR_ARCHITEW6432 }
    $isArm = ($arch -eq 'ARM64')

    $suffix = 'x64-setup.exe'
    $armSuffix = 'arm64-setup.exe'
    if ($Msi) { $suffix = '_x64_en-US.msi'; $armSuffix = '_arm64_en-US.msi' }

    $assets = @($Release.assets)
    # A ".sig" is the updater's minisign signature over the artifact, not an artifact. Suffix matching
    # already excludes them, but only by luck of the naming, so be explicit.
    $assets = $assets | Where-Object { -not $_.name.EndsWith('.sig') }

    if ($isArm) {
        $hit = $assets | Where-Object { $_.name.EndsWith($armSuffix) } | Select-Object -First 1
        if ($hit) { return $hit }
    }
    $hit = $assets | Where-Object { $_.name.EndsWith($suffix) } | Select-Object -First 1
    if ($hit -and $isArm) {
        # Not a guess: Windows on ARM runs x64 binaries under emulation. Say so rather than silently
        # installing something that does not match the machine.
        Note 'No arm64 build in this release; using the x64 one, which Windows on ARM runs emulated.'
    }
    if (-not $hit) {
        $names = ($assets | ForEach-Object { $_.name }) -join ', '
        Die "release $($Release.tag_name) has no asset ending in '$suffix'. It has: $names"
    }
    return $hit
}

function Get-Asset {
    param($Asset, [string]$Destination)

    $mb = [math]::Round($Asset.size / 1MB, 1)
    Say "Downloading $($Asset.name) ($mb MB)..."

    # Deliberately NO Authorization header on this request, even when GITHUB_TOKEN is set. Asset URLs
    # redirect to objects.githubusercontent.com, Windows PowerShell forwards request headers across
    # the redirect, and that host rejects a GitHub token with a 400 -- so authenticating a download
    # that needs no authentication is how you break it.
    try {
        Invoke-WebRequest -Uri $Asset.browser_download_url -OutFile $Destination -UseBasicParsing -TimeoutSec 900 `
            -Headers @{ 'User-Agent' = 'allmyagents-installer' }
    } catch {
        Die "download failed: $($_.Exception.Message)"
    }

    $actual = (Get-Item -LiteralPath $Destination).Length
    if ($Asset.size -gt 0 -and $actual -ne $Asset.size) {
        Die "downloaded $actual bytes but GitHub said the asset is $($Asset.size). Truncated or intercepted -- do not run it."
    }

    # Magic bytes. Without this check the commonest failure -- a proxy or captive portal answering
    # with an HTML error page -- lands as a file with the right name and the right extension that
    # msiexec then rejects with something unhelpful about the package being invalid.
    $head = New-Object byte[] 8
    $fs = [System.IO.File]::OpenRead($Destination)
    try { [void]$fs.Read($head, 0, 8) } finally { $fs.Close() }
    $hex = ($head | ForEach-Object { $_.ToString('X2') }) -join ''
    if ($Destination.EndsWith('.msi')) {
        # OLE2 compound document.
        if (-not $hex.StartsWith('D0CF11E0A1B11AE1')) { Die "that is not an MSI (file starts with $hex). Do not run it." }
    } else {
        # PE executable: "MZ".
        if (-not $hex.StartsWith('4D5A')) { Die "that is not a Windows executable (file starts with $hex). Do not run it." }
    }

    $sha = (Get-FileHash -LiteralPath $Destination -Algorithm SHA256).Hash
    Note "size $actual bytes, as published"
    Note "SHA-256 $sha"

    # There is no Authenticode certificate for this project yet, so this will say NotSigned and that
    # is expected, not a warning to bury. Report it rather than pretending it was checked.
    $sig = Get-AuthenticodeSignature -LiteralPath $Destination
    if ($sig.Status -eq 'Valid') {
        Note "signed by $($sig.SignerCertificate.Subject)"
    } else {
        Note "not code-signed ($($sig.Status)) -- expected for this project today; SmartScreen will warn on first launch."
    }
}

# ---------------------------------------------------------------------------------------------
# Installing and uninstalling the app itself
# ---------------------------------------------------------------------------------------------

function Install-Package {
    param([string]$Path)

    if ($Path.EndsWith('.msi')) {
        $log = Join-Path $env:TEMP 'allmyagents-msi.log'
        # An ARRAY, and with the quotes written INTO the element. Start-Process joins -ArgumentList
        # with spaces and adds no quoting of its own, so a %TEMP% under a profile name with a space
        # in it silently becomes two arguments. This is the same class of bug that ate a
        # --config '{"json":true}' argument in this repo's CI: PowerShell's handling of quotes when
        # handing arguments to a native command is not what it looks like.
        $msiArgs = @('/i', "`"$Path`"", '/qn', '/norestart', '/l*v', "`"$log`"")
        $p = Start-Process msiexec.exe -ArgumentList $msiArgs -Wait -PassThru
        switch ($p.ExitCode) {
            0     { Say 'Installed.' }
            3010  { Say 'Installed. Windows wants a restart to finish, but the app will run now.' }
            1602  { Die 'the installation was cancelled.' }
            1618  { Die 'another Windows Installer job is already running. Wait for it to finish and try again.' }
            1625  { Die 'system policy blocks non-administrators from installing this package. Run from an elevated shell, or use the default (non-MSI) installer, which needs no elevation.' }
            1638  { Die "this exact version is already installed. Pass -Force to reinstall it." }
            default {
                if (Test-Path $log) { Get-Content $log -Tail 40 | ForEach-Object { Write-Host "    $_" } }
                Die "msiexec failed with exit code $($p.ExitCode). Full log: $log"
            }
        }
    } else {
        # NSIS: /S is silent. tauri.conf.json sets installMode currentUser, so this lands in
        # %LOCALAPPDATA%\AllMyAgents and asks for nothing.
        $p = Start-Process -FilePath $Path -ArgumentList '/S' -Wait -PassThru
        if ($p.ExitCode -ne 0) { Die "the installer exited with code $($p.ExitCode)." }
        Say 'Installed.'
    }
}

function Uninstall-App {
    $installed = Get-InstalledApp
    if (-not $installed) { Note "$AppName does not appear to be installed."; return }

    Say "Removing $AppName $($installed.Version) ($($installed.Kind), $($installed.Scope))..."
    if ($installed.Kind -eq 'msi') {
        if ($installed.Scope -eq 'per-machine' -and -not (Test-Elevated)) {
            Die "removing a per-machine MSI install needs an elevated shell. Open PowerShell as administrator and run this again, or use Settings > Apps."
        }
        $p = Start-Process msiexec.exe -ArgumentList @('/x', $installed.ProductCode, '/qn', '/norestart') -Wait -PassThru
        if ($p.ExitCode -ne 0 -and $p.ExitCode -ne 3010) { Die "msiexec /x failed with exit code $($p.ExitCode)." }
    } else {
        $exe = $installed.UninstallString.Trim('"')
        if (-not (Test-Path -LiteralPath $exe)) { Die "the registered uninstaller is missing: $exe. Remove it via Settings > Apps." }
        $p = Start-Process -FilePath $exe -ArgumentList '/S' -Wait -PassThru
        if ($p.ExitCode -ne 0) { Die "the uninstaller exited with code $($p.ExitCode)." }
    }
    Say 'Removed.'
}

# ---------------------------------------------------------------------------------------------
# Everything above is definitions; the program starts here. Keeping that boundary means the script
# can be dot-sourced with -Help to get the functions on their own, which is how
# scripts/install-windows.tests.ps1 exercises the PATH string handling without a registry anywhere
# near it.
# ---------------------------------------------------------------------------------------------

if ($Help) { Show-Usage; return }

if ($env:OS -ne 'Windows_NT') { Die 'this installer is for Windows. On macOS use scripts/install-macos.sh.' }
if ($PSVersionTable.PSVersion.Major -lt 5) { Die "this needs PowerShell 5.1 or newer; this is $($PSVersionTable.PSVersion)." }

if ($Uninstall) {
    Remove-Shim
    Remove-UserPathEntry -Dir $BinDir
    if (-not $KeepApp) {
        Assert-NotRunning
        Uninstall-App
    }
    Write-Host ''
    Write-Host 'OK  AllMyAgents removed.' -ForegroundColor Green
    Write-Host ''
    Note 'Your agents, journals and settings are still on disk, deliberately. Delete them yourself if'
    Note 'you actually want them gone:'
    Note "  Remove-Item -Recurse '$env:LOCALAPPDATA\direct.cec.allmyagents'"
    return
}

$installed = Get-InstalledApp

if (-not $PathOnly) {
    if ($Msi -and -not (Test-Elevated)) {
        Die @"
-Msi needs an elevated shell.

The .msi is a per-machine package: its Property table sets ALLUSERS=1 and it installs into
Program Files, which needs administrator rights. msiexec /qn cannot show a UAC prompt, so it would
fail rather than ask.

Either run this from an elevated PowerShell, or drop -Msi and use the default installer, which is
per-user, lands in %LOCALAPPDATA%\AllMyAgents, and needs no elevation at all.
"@
    }

    $release = Get-Release
    $version = $release.tag_name
    Say "Latest release: $version"

    # Idempotency: a second run of the same command should be a no-op for the app and still repair
    # the command and the PATH entry, rather than reinstalling 28 MB or failing with MSI error 1638.
    if ((Test-SameVersion -Tag $version -Installed $installed.Version) -and -not $Force) {
        Say "$AppName $($installed.Version) is already installed -- skipping the download. Pass -Force to reinstall."
    } else {
        # The MSI and the -setup.exe are separate products to Windows: separate uninstall entries,
        # separate install directories, separate updater state. Installing one over the other leaves
        # two copies that both auto-update and fight over the hub's port, which presents as the app
        # "randomly" being the wrong version. Refuse to be the cause of that without being told to.
        $switchingKind = $installed -and (($installed.Kind -eq 'nsis' -and $Msi) -or ($installed.Kind -eq 'msi' -and -not $Msi))
        if ($switchingKind -and -not $Force) {
            $other = $(if ($Msi) { 'the MSI' } else { 'the default per-user installer' })
            Die "$AppName $($installed.Version) is already installed as a $($installed.Kind) package ($($installed.Scope)) at $($installed.InstallLocation). Installing it again with $other gives you two independent copies. Remove the existing one first with -Uninstall, or pass -Force if you really want both."
        }
        Assert-NotRunning

        $asset = Select-Asset -Release $release
        $tmp = Join-Path ([System.IO.Path]::GetTempPath()) ("allmyagents-" + [Guid]::NewGuid().ToString('N'))
        New-Item -ItemType Directory -Force -Path $tmp | Out-Null
        try {
            $pkg = Join-Path $tmp $asset.name
            Get-Asset -Asset $asset -Destination $pkg
            Say "Installing $version..."
            Install-Package -Path $pkg
        } finally {
            Remove-Item -Recurse -Force -LiteralPath $tmp -ErrorAction SilentlyContinue
        }
        $installed = Get-InstalledApp
    }
}

$exe = Find-Exe -Installed $installed
if (-not $exe) {
    # Say what IS there. A probe that reports absence without reporting what it found turns a
    # five-minute answer into an hour -- this repo has the commit history to prove it.
    Warn "could not find $ExeName. What is actually in the likely places:"
    foreach ($r in @((Join-Path $env:LOCALAPPDATA $AppName), (Join-Path $env:LOCALAPPDATA 'Programs'), $env:ProgramFiles)) {
        if ($r -and (Test-Path -LiteralPath $r)) {
            Get-ChildItem -LiteralPath $r -Filter '*llmy*' -Recurse -Depth 2 -ErrorAction SilentlyContinue |
                Select-Object -First 20 | ForEach-Object { Note $_.FullName }
        }
    }
    Die 'the app is not where this script expected it. Nothing was changed on your PATH.'
}

Write-Host ''
if ($NoPath) {
    Write-Host "OK  $AppName is installed at $exe" -ForegroundColor Green
    Note 'Skipped the allmyagents command (-NoPath).'
} else {
    Write-Shim -ExePath $exe
    Add-UserPathEntry -Dir $BinDir
    Write-Host ''
    Write-Host "OK  $AppName is installed at $exe" -ForegroundColor Green
    Note "Open a NEW terminal and type:  $CmdName"
}

Write-Host ''
Note 'First launch needs an internet connection -- it fetches the hub dependencies and the vendor'
Note 'CLIs from npm, which takes a couple of minutes. The window says so while it works.'
Note 'To remove it all later:  .\install-windows.ps1 -Uninstall'
